# Generated by Django 4.1.2 on 2022-10-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('pBrand', models.CharField(max_length=260)),
                ('pName', models.CharField(max_length=260)),
                ('pGen', models.CharField(max_length=260)),
                ('pCore', models.IntegerField()),
                ('pThread', models.IntegerField()),
                ('pSpeed', models.IntegerField()),
                ('pigpu', models.BooleanField()),
                ('pPrice', models.IntegerField()),
                ('pThumb', models.ImageField(upload_to='')),
            ],
        ),
    ]
