# Generated by Django 4.1.2 on 2022-10-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rams',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('rBrand', models.CharField(max_length=260)),
                ('rName', models.CharField(max_length=260)),
                ('rCap', models.IntegerField()),
                ('rSpeed', models.IntegerField()),
                ('rPrice', models.IntegerField()),
                ('rThumb', models.ImageField(upload_to='')),
            ],
        ),
    ]
