# Generated by Django 4.1.2 on 2022-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rams'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('gID', models.AutoField(primary_key=True, serialize=False)),
                ('gBrand', models.CharField(max_length=260)),
                ('gName', models.CharField(max_length=260)),
                ('gCap', models.IntegerField()),
                ('gPrice', models.IntegerField()),
                ('gThumb', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('hID', models.AutoField(primary_key=True, serialize=False)),
                ('hBrand', models.CharField(max_length=260)),
                ('hName', models.CharField(max_length=260)),
                ('hCap', models.IntegerField()),
                ('hPrice', models.IntegerField()),
                ('hThumb', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mobo',
            fields=[
                ('mID', models.AutoField(primary_key=True, serialize=False)),
                ('mBrand', models.CharField(max_length=260)),
                ('mName', models.CharField(max_length=260)),
                ('isAmdorIntel', models.BooleanField()),
                ('mPrice', models.IntegerField()),
                ('mThumb', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('sID', models.AutoField(primary_key=True, serialize=False)),
                ('sBrand', models.CharField(max_length=260)),
                ('sName', models.CharField(max_length=260)),
                ('sCap', models.IntegerField()),
                ('sInterface', models.CharField(max_length=260)),
                ('sPrice', models.IntegerField()),
                ('sThumb', models.ImageField(upload_to='')),
            ],
        ),
    ]
